export { defineCollection, defineCollections, defineConfig } from '@pagesmith/core'
export {
  createContentLayer,
  ContentEntry,
  processMarkdown,
  extractFrontmatter,
  validateFrontmatter,
  extractToc,
  convert,
  BaseFrontmatterSchema,
  BlogFrontmatterSchema,
  HeadingSchema,
  MarkdownConfigSchema,
  ProjectFrontmatterSchema,
  builtinMarkdownValidators,
  codeBlockValidator,
  createLinkValidator,
  headingValidator,
  linkValidator,
  runValidators,
  defaultIncludePatterns,
  JsoncLoader,
  JsonLoader,
  LoaderError,
  MarkdownLoader,
  resolveLoader,
  registerLoader,
  TomlLoader,
  YamlLoader,
  z,
} from '@pagesmith/core'
export type {
  BaseFrontmatter,
  BlogFrontmatter,
  CollectionComputed,
  CollectionDef,
  CollectionMap,
  ContentLayer,
  ContentLayerConfig,
  ContentPlugin,
  ContentValidator,
  ConvertOptions,
  ConvertResult,
  FrontmatterResult,
  Heading,
  InferCollectionData,
  InferCollectionLoaderKind,
  LayerConvertOptions,
  Loader,
  LoaderResult,
  LoaderType,
  MarkdownConfig,
  MarkdownResult,
  ProjectFrontmatter,
  RawEntry,
  RenderedContent,
  ResolvedValidatorContext,
  TypedContentLayer,
  ValidationEntryResult,
  ValidationIssue,
  ValidationResult,
  ValidatorContext,
  WatchCallback,
  WatchEvent,
  WatchHandle,
} from '@pagesmith/core'

export {
  SiteAnalyticsConfigSchema,
  SiteCopyrightSchema,
  defineSiteConfig,
  loadSiteConfig,
  normalizeBasePath,
  normalizePresetSpecifier,
  parseSiteConfig,
  resolveSitePresetSpecifier,
  SiteFooterLinkGroupSchema,
  SiteFooterLinkSchema,
  SiteMaintainerSchema,
  SiteSearchConfigSchema,
  SiteSeoConfigSchema,
  SiteServerConfigSchema,
  SiteSidebarConfigSchema,
  SiteThemeConfigSchema,
  SiteUserConfigSchema,
  normalizeOrigin,
  stripBasePath,
  withBasePath,
  withTrailingSlash,
} from './config.js'
export { formatPath, withoutTrailingSlash } from './components/utils.js'
export type {
  RawSiteConfig,
  SiteAnalyticsConfig,
  SiteCopyright,
  SiteFooterLink,
  SiteFooterLinkGroup,
  SiteMaintainer,
  SiteSearchConfig,
  SiteSeoConfig,
  SiteServerConfig,
  SiteSidebarConfig,
  SiteThemeConfig,
  SiteUserConfig,
} from './config.js'
export type { SitePageMeta } from './components/document.js'
export type { SiteBuildOptions, SiteDevOptions, SiteLogLevel, SitePreset } from './preset.js'

export {
  sortByManualOrder,
  sortByDate,
  buildBreadcrumbs,
  buildSidebarFromEntries,
  buildPrevNext,
} from './content-helpers.js'

export {
  validateBuildOutput,
  runBuildValidation,
  type BuildValidatorOptions,
  type BuildValidationIssue,
  type BuildValidationResult,
} from './build-validator.js'

export const SITE_PACKAGE_NAME = '@pagesmith/site'
