import { afterEach, describe, expect, it } from 'vite-plus/test'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { defineCollection, defineCollections, z } from '../index.js'
import { pagesmithContent } from './index.js'

describe('@pagesmith/site/vite pagesmithContent', () => {
  let tempDir = ''

  afterEach(() => {
    if (tempDir) {
      rmSync(tempDir, { recursive: true, force: true })
      tempDir = ''
    }
  })

  it('keeps generated dts imports on the site public surface', () => {
    tempDir = mkdtempSync(join(tmpdir(), 'ps-site-content-dts-'))
    mkdirSync(join(tempDir, 'content', 'posts'), { recursive: true })
    mkdirSync(join(tempDir, 'src'), { recursive: true })
    writeFileSync(join(tempDir, 'content.config.ts'), 'export default {}\n', 'utf-8')

    const collections = defineCollections({
      posts: defineCollection({
        loader: 'markdown',
        directory: 'content/posts',
        schema: z.object({
          title: z.string(),
        }),
      }),
    })

    const plugin = pagesmithContent({
      collections,
      configPath: 'content.config.ts',
      dts: { path: 'src/pagesmith-content.d.ts' },
    })

    plugin.configResolved?.({ root: tempDir })
    plugin.buildStart?.()

    const dtsSource = readFileSync(join(tempDir, 'src', 'pagesmith-content.d.ts'), 'utf-8')
    expect(dtsSource).toContain('Generated by @pagesmith/site/vite')
    expect(dtsSource).toContain("import('@pagesmith/site/vite').ContentModuleMap")
    expect(dtsSource).toContain("import('@pagesmith/site/vite').ContentCollectionModule")
    expect(dtsSource).not.toContain('@pagesmith/core/vite')
  })
})
