// Generated by @pagesmith/core/vite. Do not edit manually.
type __PagesmithCollections = typeof import('../../shared-content/content.config').default

declare module 'virtual:content' {
  const content: import('@pagesmith/core/vite').ContentModuleMap<__PagesmithCollections>
  export default content
}

declare module 'virtual:content/posts' {
  const collection: import('@pagesmith/core/vite').ContentCollectionModule<
    __PagesmithCollections["posts"]
  >
  export default collection
}

declare module 'virtual:content/authors' {
  const collection: import('@pagesmith/core/vite').ContentCollectionModule<
    __PagesmithCollections["authors"]
  >
  export default collection
}

declare module 'virtual:content/pages' {
  const collection: import('@pagesmith/core/vite').ContentCollectionModule<
    __PagesmithCollections["pages"]
  >
  export default collection
}
