import { join } from 'path'
import { describe, expect, it } from 'vite-plus/test'
import { createDtsSource } from '../vite/dts'

describe('createDtsSource', () => {
  const dtsPath = join('/repo', 'src', 'pagesmith-content.d.ts')
  const configPath = join('/repo', 'content.config.ts')

  it('uses core/vite types by default', () => {
    const source = createDtsSource('virtual:content', ['posts'], dtsPath, configPath)

    expect(source).toContain('Generated by @pagesmith/core/vite')
    expect(source).toContain("import('@pagesmith/core/vite').ContentModuleMap")
    expect(source).toContain("import('@pagesmith/core/vite').ContentCollectionModule")
  })

  it('can target a different public Vite entry point', () => {
    const source = createDtsSource(
      'virtual:content',
      ['posts'],
      dtsPath,
      configPath,
      '@pagesmith/site/vite',
    )

    expect(source).toContain('Generated by @pagesmith/site/vite')
    expect(source).toContain("import('@pagesmith/site/vite').ContentModuleMap")
    expect(source).toContain("import('@pagesmith/site/vite').ContentCollectionModule")
    expect(source).not.toContain('@pagesmith/core/vite')
  })
})
