export const PAGESMITH_TITLE = 'Pagesmith'
export const DEFAULT_SKILL_NAME = 'pagesmith'

export function renderSharedOverview(): string {
  return [
    `${PAGESMITH_TITLE} is a filesystem-first content toolkit with three public packages: \`@pagesmith/core\` (headless content layer), \`@pagesmith/site\` (site toolkit and \`pagesmith-site\`), and \`@pagesmith/docs\` (opinionated docs preset and \`pagesmith-docs\`).`,
    '',
    'Use Pagesmith when you need:',
    '- schema-validated content collections loaded from the filesystem',
    '- lazy markdown rendering with headings and read-time metadata',
    '- framework-agnostic content APIs for React, Solid, Svelte, vanilla JS, Node, Bun, or Deno',
    '',
    'Core APIs:',
    '- `defineCollection({...})` to define a typed collection',
    '- `defineConfig({...})` to group collections and markdown options',
    '- `createContentLayer(config)` to query content and run validation',
    '- `entry.render()` to convert markdown on demand',
    '',
    'Site APIs:',
    '- `pagesmith-site` CLI for preset-driven dev/build/preview flows',
    '- `@pagesmith/site/jsx-runtime` for server-side TSX',
    '- `@pagesmith/site/vite` for SSG helpers',
    '',
    'Working rules:',
    '- for first-time content-layer setup or retrofit work, start with `node_modules/@pagesmith/core/ai-guidelines/setup-core.md`',
    '- for custom site setup on top of core, start with `node_modules/@pagesmith/site/ai-guidelines/setup-site.md`',
    '- prefer folder-based markdown entries when content references sibling assets',
    '- follow the markdown guidelines in `.pagesmith/markdown-guidelines.md` when authoring content',
    '- use fenced code blocks with a language identifier, one h1 per page, sequential heading depth',
  ].join('\n')
}

export function renderDocsOverview(): string {
  return [
    'Docs-specific rules:',
    '- `@pagesmith/docs` is convention-based and builds a static docs site from `content/` plus `pagesmith.config.json5`',
    '- top-level content folders become top navigation sections (for example `guide/`, `reference/`, `packages/`)',
    '- for first-time docs setup or retrofit work, read `node_modules/@pagesmith/docs/ai-guidelines/setup-docs.md` before choosing or creating a docs folder',
    '- prefer `pagesmith-docs init` for bootstrap work; for GitHub repos it should default to `basePath: "/<repo-name>"` and probe `https://<owner>.github.io` for the origin',
    '- folder-based markdown entries should prefer `README.md` or `index.md` when a page owns sibling assets or diagrams',
    '- the home page is `content/README.md`; optional home-specific data can live in `content/home.json5`',
    '- sidebar labels, nav labels, and ordering live in frontmatter (`sidebarLabel`, `navLabel`, `order`)',
    '- when a page needs a diagram, keep the editable source file and rendered assets beside the page; raw `mermaid`, `dot`, `excalidraw`, and `drawio` fences are code examples unless the project configured a custom renderer',
    '- footer links live in `pagesmith.config.json5` under `footerLinks`; they can be a flat wrapped row of links or grouped columns with optional headers, and when omitted the footer reuses the major top-level nav links',
    '- the footer legal line combines `copyright` with the default Pagesmith sign-off, which can include a maintainer credit from `maintainer` or `package.json` author',
    '- Pagefind search is built in; do not recommend a separate search plugin package',
    '- layout overrides use fixed keys under `theme.layouts` such as `home`, `page`, and `notFound`',
    '- use `.only-light` and `.only-dark` on images when a diagram or screenshot needs different light/dark renders',
    '- use the version-matched schema files in `node_modules/@pagesmith/docs/schemas/` when authoring `pagesmith.config.json5`, `meta.json5`, and docs frontmatter; when the config lives at the repo root, keep `$schema` pointing at `./node_modules/@pagesmith/docs/schemas/pagesmith-config.schema.json`',
    '- for MCP-compatible tooling, prefer `pagesmith-docs mcp --stdio` from the `@pagesmith/docs` package',
  ].join('\n')
}

export function renderCoreQuickStart(): string {
  return [
    '```ts',
    "import { createContentLayer, defineCollection, defineConfig, z } from '@pagesmith/core'",
    '',
    'const posts = defineCollection({',
    "  loader: 'markdown',",
    "  directory: 'content/posts',",
    '  schema: z.object({',
    '    title: z.string(),',
    '    description: z.string().optional(),',
    '    date: z.coerce.date(),',
    '    tags: z.array(z.string()).default([]),',
    '  }),',
    '})',
    '',
    'const layer = createContentLayer(',
    '  defineConfig({',
    '    collections: { posts },',
    '  }),',
    ')',
    '',
    "const entries = await layer.getCollection('posts')",
    'const rendered = await entries[0]?.render()',
    '```',
  ].join('\n')
}

export function renderDocsQuickStart(): string {
  return [
    '```json5',
    '// pagesmith.config.json5',
    '{',
    "  $schema: './node_modules/@pagesmith/docs/schemas/pagesmith-config.schema.json',",
    "  name: 'Acme Docs',",
    "  title: 'Acme Docs',",
    "  origin: 'https://acme.github.io',",
    "  basePath: '/acme-docs',",
    "  description: 'Multi-package documentation',",
    "  contentDir: './content',",
    "  outDir: './gh-pages',",
    '  maintainer: {',
    "    name: 'Sujeet Jaiswal',",
    "    link: 'https://sujeet.pro',",
    '  },',
    '  copyright: {',
    "    projectName: 'Acme Docs',",
    '    startYear: 2024,',
    '    endYear: null,',
    '  },',
    '  footerLinks: [',
    '    {',
    "      header: 'Docs',",
    '      links: [',
    "        { label: 'Guide', path: '/guide' },",
    "        { label: 'Reference', path: '/reference' },",
    '      ],',
    '    },',
    '  ],',
    '  editLink: {',
    "    repo: 'https://github.com/acme/docs',",
    '  },',
    '  search: { enabled: true },',
    '}',
    '```',
    '',
    '```text',
    'content/',
    '  README.md                 # Home page (DocHome layout)',
    '  guide/',
    '    meta.json5              # Section ordering',
    '    getting-started/',
    '      README.md             # A page',
    '  reference/',
    '    api/README.md',
    '```',
  ].join('\n')
}

export function renderMarkdownGuidelines(): string {
  return [
    '# Pagesmith Markdown Guidelines',
    '',
    'Markdown feature support for content authored with `@pagesmith/core` and `@pagesmith/docs`.',
    '',
    '## Pipeline Order',
    '',
    '```',
    'remark-parse → remark-gfm → remark-frontmatter',
    '  → remark-github-alerts → remark-smartypants → remark-math (when `markdown.math` is enabled or auto-detected) → [user remark plugins]',
    '  → remark-rehype',
    '  → rehype-mathjax (when math is enabled)',
    '  → applyPagesmithCodeRenderer (dual themes, line numbers, titles, copy, collapse, mark/ins/del)',
    '  → rehype-code-tabs → rehype-scrollable-tables',
    '  → rehype-slug → rehype-autolink-headings',
    '  → rehype-external-links → rehype-accessible-emojis',
    '  → heading extraction → [user rehype plugins] → rehype-stringify',
    '```',
    '',
    '## Key Rules',
    '',
    '- Use fenced code blocks with a language identifier (validator warns otherwise)',
    '- One `# h1` per page (validator enforces)',
    '- Sequential heading depth (no skipping from h2 to h4)',
    '- Prefer relative links for internal content',
    '- `allowDangerousHtml` defaults to `true`; disable it when rendering untrusted markdown',
    "- `math` defaults to `'auto'`; Pagesmith only enables the math plugins when the page contains math markers",
    '- Do NOT add manual copy-button JS inside markdown content — the built-in renderer injects its own copy/collapse runtime',
    '- Include the shipped Pagesmith markdown CSS so code block chrome and tabs render correctly',
    '- Raw `mermaid`, `dot`, `excalidraw`, and `drawio` fences are source examples, not rendered diagrams, unless the project adds a custom renderer',
    '',
    '## Supported Features',
    '',
    '| Feature | Syntax | Notes |',
    '|---|---|---|',
    '| GFM tables | `\\| col \\| col \\|` | Alignment via `:---`, `:---:`, `---:` |',
    '| Strikethrough | `~~text~~` | |',
    '| Task lists | `- [x] done` / `- [ ] todo` | |',
    '| Footnotes | `[^id]` + `[^id]: text` | |',
    '| Alerts | `> [!NOTE]`, `> [!TIP]`, `> [!IMPORTANT]`, `> [!WARNING]`, `> [!CAUTION]` | GitHub-compatible |',
    '| Inline math | `$E = mc^2$` | No spaces inside delimiters |',
    '| Block math | `$$...$$` | Rendered via MathJax |',
    '| Smart quotes | `"text"` → curly quotes | Automatic |',
    '| Em/en dash | `---` / `--` | Automatic |',
    '| External links | `[text](https://...)` | Auto `target="_blank"` |',
    '| Heading anchors | Auto `id` + wrapped anchor | All headings |',
    '| Accessible emoji | Unicode emoji | Auto `role="img"` + `aria-label` |',
    '',
    '## Code Block Features (Built-in Renderer)',
    '',
    '| Meta | Example | Description |',
    '|---|---|---|',
    '| `title="..."` | `` ```js title="app.js" `` | File title |',
    '| `showLineNumbers` | `` ```js showLineNumbers `` | Line numbers |',
    '| `mark={lines}` | `` ```js mark={3,5-7} `` | Highlight lines |',
    '| `ins={lines}` | `` ```js ins={4} `` | Inserted lines (green) |',
    '| `del={lines}` | `` ```js del={5} `` | Deleted lines (red) |',
    '| `collapse={lines}` | `` ```js collapse={1-5} `` | Collapsible section |',
    '| `wrap` | `` ```js wrap `` | Text wrapping |',
    '| `frame="..."` | `` ```js frame="terminal" `` | Frame style |',
    '',
    '## Diagrams And Source-Only Fences',
    '',
    'Pagesmith does not ship an inline Mermaid, Graphviz, Excalidraw, or draw.io renderer.',
    '',
    '- `mermaid`, `dot`, and `plantuml` are highlighted as text',
    '- `excalidraw` is highlighted as JSON and `drawio` as XML',
    '- raw diagram fences publish as code blocks unless the project adds a custom renderer',
    '- for published docs, generate image assets from diagram source and embed the rendered SVG or PNG',
    '- in docs projects, use `.only-light` and `.only-dark` when light and dark diagram variants differ',
    '- choose Mermaid for text-first flows, Excalidraw for architecture sketches, draw.io for precise infrastructure diagrams, and Graphviz for dependency graphs',
    '',
    '## Built-in Content Validators',
    '',
    '- **linkValidator** — warns on bare URLs, empty link text, suspicious protocols',
    '- **headingValidator** — enforces single h1, sequential depth, non-empty text',
    '- **codeBlockValidator** — warns on missing language, unknown meta properties',
    '',
    'Known valid meta properties: `title`, `showLineNumbers`, `startLineNumber`, `wrap`, `frame`, `collapse`, `mark`, `ins`, `del`.',
  ].join('\n')
}

export function renderLlmsTxt(): string {
  return [
    '# Pagesmith',
    '',
    '> Pagesmith is a filesystem-first content toolkit with `@pagesmith/core`, `@pagesmith/site`, and `@pagesmith/docs`.',
    '',
    '## @pagesmith/core — Content Layer',
    '',
    'Schema-validated content collections, lazy markdown rendering with a built-in Shiki-backed code renderer, validation, loaders, schemas, and the Vite content plugin.',
    '',
    '### Basic Setup',
    '',
    'Start with `node_modules/@pagesmith/core/ai-guidelines/setup-core.md` for bootstrap or retrofit work.',
    '',
    renderCoreQuickStart(),
    '',
    '### Vite Integration',
    '',
    '```ts',
    "import { pagesmithContent } from '@pagesmith/core/vite'",
    "import collections from './content.config'",
    '',
    'export default defineConfig({',
    '  plugins: [',
    '    pagesmithContent({ collections }),',
    '  ],',
    '})',
    '```',
    '',
    "Import collections as virtual modules: `import posts from 'virtual:content/posts'`",
    '',
    '## @pagesmith/site — Site Toolkit',
    '',
    'Preset-driven `pagesmith-site` CLI, JSX runtime, shared CSS/runtime behavior, Vite SSG helpers, and shared site utilities on top of core.',
    '',
    '### Typical split',
    '',
    'Start with `node_modules/@pagesmith/site/ai-guidelines/setup-site.md` for bootstrap or retrofit work.',
    '',
    '```ts',
    "import { pagesmithContent } from '@pagesmith/core/vite'",
    "import { pagesmithSsg, sharedAssetsPlugin } from '@pagesmith/site/vite'",
    '```',
    '',
    '## @pagesmith/docs — Documentation Sites',
    '',
    'Convention-based docs preset with default theme, Pagefind search, sidebar generation, listing pages, and layout overrides.',
    '',
    '### Basic Setup',
    '',
    'Start with `node_modules/@pagesmith/docs/ai-guidelines/setup-docs.md` for bootstrap or retrofit work.',
    '',
    renderDocsQuickStart(),
    '',
    '### Layout Overrides',
    '',
    '```json5',
    '{',
    '  theme: {',
    '    layouts: {',
    "      home: './theme/layouts/DocHome.tsx',",
    "      page: './theme/layouts/DocPage.tsx',",
    "      notFound: './theme/layouts/DocNotFound.tsx',",
    '    },',
    '  },',
    '}',
    '```',
    '',
    '### CLI',
    '',
    '```bash',
    'pagesmith-docs init --ai   # Initialize config + content + AI integrations',
    'pagesmith-docs dev         # Development server',
    'pagesmith-docs build       # Production build',
    'pagesmith-docs preview     # Preview built site',
    'pagesmith-docs mcp --stdio # Start MCP server for AI agents',
    '```',
  ].join('\n')
}

export function renderLlmsFullTxt(): string {
  return [
    '# Pagesmith — Full LLM Reference',
    '',
    renderSharedOverview(),
    '',
    '---',
    '',
    '## @pagesmith/core',
    '',
    '### Content Layer API',
    '',
    '| Method | Description |',
    '|---|---|',
    '| `createContentLayer(config)` | Create a content layer |',
    '| `layer.getCollection(name)` | Load all entries (cached) |',
    '| `layer.getEntry(collection, slug)` | Get single entry by slug |',
    '| `layer.convert(markdown, options?)` | Convert raw markdown to HTML |',
    '| `layer.validate(collection?)` | Run all validators |',
    '| `layer.invalidate(collection, slug)` | Cache-bust a single entry |',
    '| `layer.invalidateAll()` | Cache-bust all collections |',
    '',
    '### Collection Options',
    '',
    '| Option | Type | Description |',
    '|---|---|---|',
    "| `loader` | `string \\| Loader` | `'markdown'`, `'json'`, `'json5'`, `'jsonc'`, `'yaml'`, `'toml'`, or custom |",
    '| `directory` | `string` | Directory containing files |',
    '| `schema` | `z.ZodType` | Zod schema for validation |',
    '| `include` | `string[]` | Glob include patterns |',
    '| `exclude` | `string[]` | Glob exclude patterns |',
    '| `computed` | `Record<string, fn>` | Computed fields |',
    '| `validate` | `fn` | Custom validation |',
    '| `filter` | `fn` | Filter entries |',
    '| `slugify` | `fn` | Custom slug generation |',
    '| `transform` | `fn` | Pre-validation transform |',
    '| `validators` | `ContentValidator[]` | Custom content validators |',
    '| `disableBuiltinValidators` | `boolean` | Disable link/heading/code-block validators |',
    '',
    '### Vite Plugins',
    '',
    renderCoreQuickStart(),
    '',
    '```ts',
    '// Content plugin only',
    "import { pagesmithContent } from '@pagesmith/core/vite'",
    "import collections from './content.config'",
    '',
    'export default defineConfig({',
    '  plugins: [',
    '    pagesmithContent({ collections }),',
    '  ],',
    '})',
    '```',
    '',
    '### Frontmatter Schemas',
    '',
    '- `BaseFrontmatterSchema` — title, description, publishedDate, lastUpdatedOn, tags, draft',
    '- `BlogFrontmatterSchema` — extends base + category, featured, coverImage',
    '- `ProjectFrontmatterSchema` — extends base + gitRepo, links',
    '',
    '### Export Map',
    '',
    '| Import Path | Purpose |',
    '|---|---|',
    '| `@pagesmith/core` | Main API (defineCollection, createContentLayer, z, etc.) |',
    '| `@pagesmith/core/markdown` | processMarkdown |',
    '| `@pagesmith/core/schemas` | Zod schemas and types |',
    '| `@pagesmith/core/loaders` | Loader classes and registry |',
    '| `@pagesmith/core/assets` | Asset copying and hashing |',
    '| `@pagesmith/core/vite` | `pagesmithContent` |',
    '| `@pagesmith/core/mcp` | MCP server for AI agents |',
    '',
    '---',
    '',
    '## @pagesmith/site',
    '',
    '- `pagesmith-site` CLI',
    '- `@pagesmith/site/jsx-runtime` for server-side TSX',
    '- `@pagesmith/site/css/*` for shared styles',
    '- `@pagesmith/site/runtime/*` for TOC, theme, and code-block behavior',
    '- `@pagesmith/site/vite` for `pagesmithSsg`, `sharedAssetsPlugin`, and `prerenderRoutes`',
    '- `@pagesmith/site/ssg-utils` for shared site helpers',
    '',
    '---',
    '',
    '## @pagesmith/docs',
    '',
    '### Configuration (pagesmith.config.json5)',
    '',
    '| Field | Type | Default | Description |',
    '|---|---|---|---|',
    '| `name` | `string` | — | Site name (header) |',
    '| `title` | `string` | — | Browser tab title |',
    '| `description` | `string` | — | Meta description |',
    '| `origin` | `string` | — | Production URL |',
    '| `language` | `string` | `en` | HTML lang |',
    '| `contentDir` | `string` | `content` | Content path |',
    '| `outDir` | `string` | `dist` | Output path |',
    '| `basePath` | `string` | `/` | URL base |',
    '| `maintainer` | `object` | `package.json author` | Maintainer credit for the default footer sign-off |',
    '| `footerLinks` | `array` | `top-level nav links` | Footer links as a flat row or grouped columns |',
    '| `copyright` | `object` | — | Footer legal line config (`projectName`, `startYear`, `endYear`) |',
    '| `sidebar.collapsible` | `boolean` | `true` | Collapsible sidebar |',
    '| `search.enabled` | `boolean` | `true` | Pagefind search |',
    '| `preset` | `string` | — | Explicit preset specifier for the `pagesmith-site` CLI |',
    '| `presets` | `string[]` | — | Preset list; the first item is used when `preset` is absent |',
    '| `theme.layouts` | `Record` | — | Layout overrides |',
    '| `editLink` | `object \\| false` | `auto-detected` | Edit link config or explicit disable |',
    '| `lastUpdated` | `boolean` | `true` | Git-based page timestamps |',
    '| `markdown` | `MarkdownConfig` | — | Pipeline config |',
    '',
    '### Content Structure',
    '',
    renderDocsQuickStart(),
    '',
    '### Page Frontmatter',
    '',
    '| Field | Type | Description |',
    '|---|---|---|',
    '| `title` | `string` | Page title |',
    '| `description` | `string` | Meta description |',
    '| `navLabel` | `string` | Override top nav label |',
    '| `sidebarLabel` | `string` | Override sidebar label |',
    '| `order` | `number` | Manual sort order |',
    '| `draft` | `boolean` | Exclude from build |',
    '',
    '### Home Page Frontmatter',
    '',
    '| Field | Type | Description |',
    '|---|---|---|',
    '| `layout` | `string` | Built-in layouts include `home`, `page`, `listing`, and `notFound` |',
    '| `tagline` | `string` | Short description |',
    '| `install` | `string` | Install command |',
    "| `actions` | `array` | CTA buttons (`{ text, link, theme: 'brand' \\| 'alt' }`) |",
    '| `features` | `array` | Feature cards (`{ icon?, title, details }`) |',
    '| `packages` | `array` | Package cards (`{ name, description, href, tag }`) |',
    '| `codeExample` | `object` | Code example (`{ label, title, code }`) |',
    '| `chrome` | `object` | Per-page shell toggles (`header`, `sidebar`, `toc`, `footer`) |',
    '',
    '### Section Meta (meta.json5)',
    '',
    '| Field | Type | Description |',
    '|---|---|---|',
    '| `displayName` | `string` | Section label in sidebar |',
    '| `items` | `string[]` | Manual page order (slugs) |',
    '| `series` | `array` | Group pages into series |',
    '| `collapsed` | `boolean` | Start sidebar collapsed |',
    '| `orderBy` | `string` | `manual` or `publishedDate` |',
    '| `layout` | `string` | Section layout override |',
    '| `itemLayout` | `string` | Default layout for child pages in the section |',
    '',
    '### Layout Overrides',
    '',
    '```json5',
    '{ theme: { layouts: { home: "./layouts/Home.tsx", page: "./layouts/Page.tsx", listing: "./layouts/Listing.tsx" } } }',
    '```',
    '',
    'All layouts receive: `content`, `frontmatter`, `headings`, `slug`, `site`.',
    'Page layout adds: `sidebarSections`, `prev`, `next`.',
    '',
    '### CLI',
    '',
    '```bash',
    'pagesmith-docs init [--ai] [--config path]   # Initialize project',
    'pagesmith-docs dev [--port N] [--open]       # Dev server',
    'pagesmith-docs build [--out-dir path]        # Production build',
    'pagesmith-docs preview [--port N]            # Preview built site',
    'pagesmith-docs mcp --stdio                   # Start docs MCP server',
    '```',
    '',
    '---',
    '',
    '## Markdown Pipeline',
    '',
    renderMarkdownGuidelines(),
    '',
    '---',
    '',
    '## AI Setup',
    '',
    '```bash',
    'npx pagesmith-core ai --profile default   # AI artifacts for core/site projects',
    'npx pagesmith-docs init --ai              # Docs scaffold + AI artifacts',
    '```',
    '',
    'Generates CLAUDE.md, AGENTS.md, GEMINI.md, skills, markdown guidelines, llms.txt, and llms-full.txt.',
    '',
  ].join('\n')
}
