import { existsSync } from 'fs'
import { dirname, relative, resolve } from 'path'
import type { PagesmithContentPluginOptions } from './content-plugin'

function stripExtension(filePath: string): string {
  return filePath.replace(/\.(c|m)?[jt]sx?$/u, '')
}

function normalizePath(value: string): string {
  return value.replace(/\\/g, '/')
}

export function resolveDtsPath(
  projectRoot: string,
  dts: PagesmithContentPluginOptions<any>['dts'],
): string {
  if (dts === false) {
    return ''
  }

  if (typeof dts === 'string') {
    return resolve(projectRoot, dts)
  }

  if (typeof dts === 'object' && dts?.path) {
    return resolve(projectRoot, dts.path)
  }

  const srcPath = resolve(projectRoot, 'src')
  if (existsSync(srcPath)) {
    return resolve(srcPath, 'pagesmith-content.d.ts')
  }

  return resolve(projectRoot, 'pagesmith-content.d.ts')
}

export function createDtsSource(
  moduleId: string,
  collectionNames: string[],
  dtsPath: string,
  configPath: string,
): string {
  const configImportPath = normalizePath(
    stripExtension(relative(dirname(dtsPath), configPath)).replace(/^[^.]/u, './$&'),
  )

  const moduleLines = collectionNames
    .map(
      (name) => `declare module '${moduleId}/${name}' {
  const collection: import('@pagesmith/core/vite').ContentCollectionModule<
    __PagesmithCollections['${name.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}']
  >
  export default collection
}`,
    )
    .join('\n\n')

  return `// Generated by @pagesmith/core/vite. Do not edit manually.
type __PagesmithCollections = typeof import('${configImportPath}').default

declare module '${moduleId}' {
  const content: import('@pagesmith/core/vite').ContentModuleMap<__PagesmithCollections>
  export default content
}

${moduleLines}
`
}
